# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.CharField(db_index=True, max_length=12)),
                ('property_type', models.CharField(choices=[('D', 'Detached'), ('S', 'Semi - Detached'), ('T', 'Terraced'), ('F', 'Flats / Maisonettes'), ('O', 'Other')], max_length=1)),
                ('age', models.CharField(choices=[('Y', 'Yearly new built'), ('N', 'Established residential building')], max_length=1)),
                ('duration', models.CharField(choices=[('F', 'Freehold'), ('N', 'Leasehold')], max_length=1)),
                ('ppd', models.CharField(choices=[('A', 'Standard price paid'), ('B', 'Additional price paid')], max_length=1)),
                ('paon_saon', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('transfer_date', models.DateField(db_index=True)),
                ('transaction_id', models.IntegerField()),
                ('type_of_update', models.CharField(choices=[('C', 'Change'), ('A', 'New sale')], max_length=1)),
                ('abode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='properties.Property')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together=set([('post_code', 'paon_saon', 'street')]),
        ),
    ]
