# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type_of_update',
        ),
    ]
