# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_transaction_type_of_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tid',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
